apiVersion: v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: voting-app
    name: postgres-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
        name: postgres-pod
        app: voting-app
        
  template:
    metadata:
      name: postgres-pod
      labels:
          name: postgres-pod
          app: voting-app

    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgress"
            
          - name: POSTGRES_PASSWORD
            value: "postgress"

