apiVersion: v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: voting-app
    name: result-app-deployment
    
spec:
  replicas: 1
  selector:
    matchLabels:
        name: result-app-pod
        app: voting-app
        
  template:
    metadata:
      name: result-app-pod
      labels:
          name: result-app-pod
          app: voting-app

    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:v1
        name: result-app
        ports:
          - containerPort: 80

