apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
      name: vonting-service
      app: voting-app
spec:
  type: NodePort
  selector:
     name: voting-app-pod
     app: voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004