apiVersion: v1
kind: Pod
metadata:
    name: worker-pod
    labels:
        name: worker-pod
        app: voting-app

spec:
  containers:
  - image: kodekloud/examplevotingapp_worker:v1
    name: worker-app
