apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
      name: postress-service
      app: voting-app
spec:
  type: ClusterIP
  selector:
     name: postgres-pod
     app: voting-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432